/**
 * CANONICAL TEACHER ACTION CONTRACT
 *
 * This file is the single source of truth for symbolic teacher actions used by
 * policy, condition specs, rendering, logging, and runner inspection.
 *
 * Actions describe what pedagogical move was chosen. They do not encode why it
 * was chosen or how it is rendered into visible teacher behaviour.
 */

export const TEACHER_ACTIONS = Object.freeze({
  CONTINUE_STANDARD: 'ACTION_CONTINUE_STANDARD',
  REFRAME_PROMPT_VARIANT: 'ACTION_REFRAME_PROMPT_VARIANT',
  REQUEST_CHECKIN: 'ACTION_REQUEST_CHECKIN',

  GIVE_HINT: 'ACTION_GIVE_HINT',
  GIVE_SCAFFOLD: 'ACTION_GIVE_SCAFFOLD',
  PROVIDE_WORKED_EXAMPLE: 'ACTION_PROVIDE_WORKED_EXAMPLE',
  GIVE_BOTTOM_OUT: 'ACTION_GIVE_BOTTOM_OUT',
  CALL_DYNAMIC_HINT: 'ACTION_CALL_DYNAMIC_HINT',

  OFFER_CHOICE: 'ACTION_OFFER_CHOICE',

  GIVE_GENERAL_ENCOURAGEMENT: 'ACTION_GIVE_GENERAL_ENCOURAGEMENT',
  GIVE_SPECIFIC_PRAISE: 'ACTION_GIVE_SPECIFIC_PRAISE',
  ADDRESS_FRUSTRATION: 'ACTION_ADDRESS_FRUSTRATION',

  SUGGEST_SLOWER_PACE: 'ACTION_SUGGEST_SLOWER_PACE',
  SUGGEST_BREAK: 'ACTION_SUGGEST_BREAK',
  SKIP_OPTIONAL_CONTENT: 'ACTION_SKIP_OPTIONAL_CONTENT'
});

export const ACTION_FAMILIES = Object.freeze({
  CORE: [
    TEACHER_ACTIONS.CONTINUE_STANDARD,
    TEACHER_ACTIONS.REFRAME_PROMPT_VARIANT,
    TEACHER_ACTIONS.REQUEST_CHECKIN
  ],
  SUPPORT: [
    TEACHER_ACTIONS.GIVE_HINT,
    TEACHER_ACTIONS.GIVE_SCAFFOLD,
    TEACHER_ACTIONS.PROVIDE_WORKED_EXAMPLE,
    TEACHER_ACTIONS.GIVE_BOTTOM_OUT,
    TEACHER_ACTIONS.CALL_DYNAMIC_HINT
  ],
  AUTONOMY: [
    TEACHER_ACTIONS.OFFER_CHOICE
  ],
  AFFECT: [
    TEACHER_ACTIONS.GIVE_GENERAL_ENCOURAGEMENT,
    TEACHER_ACTIONS.GIVE_SPECIFIC_PRAISE,
    TEACHER_ACTIONS.ADDRESS_FRUSTRATION
  ],
  PACING: [
    TEACHER_ACTIONS.SUGGEST_SLOWER_PACE,
    TEACHER_ACTIONS.SUGGEST_BREAK,
    TEACHER_ACTIONS.SKIP_OPTIONAL_CONTENT
  ]
});

export const ALL_TEACHER_ACTIONS = Object.freeze(Object.values(TEACHER_ACTIONS));

export default { TEACHER_ACTIONS, ACTION_FAMILIES, ALL_TEACHER_ACTIONS };
